// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ojexxfiawjqdqwvloiax.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9qZXh4Zmlhd2pxZHF3dmxvaWF4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4NTc4NzMsImV4cCI6MjA3MzQzMzg3M30.ni52OBWIZeOEN1gfT9sJLvBfyhBuPhTLz3bbibB0-F4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});